#!/bin/bash

#
# This file is part of the FreeInstallServer.
# (c) 2011  Simon Leblanc <contact@leblanc-simon.eu>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#

lamp_default_mysql_pass=""
lamp_default_php=""

lamp_php4_version="4.4.9"   # C'est la dernière version, donc on la met en dur
lamp_php52_version="5.2.17" # C'est la dernière version, donc on la met en dur
lamp_php53_version=`wget -O - -q --user-agent="wget with FreeInstallServer" http://www.php.net | grep "Current PHP 5.3 Stable:" | sed -r 's/(5\.3\.[0-9]+)/--delete-before-- \1 --delete-after--/' | sed 's/.*--delete-before-- //' | sed 's/ --delete-after--.*//'`
lamp_php54_version=`curl -O - -q --user-agent="wget with FreeInstallServer" http://www.php.net | grep "Current PHP 5.4 Stable:" | sed -r 's/(5\.4\.[0-9]+)/--delete-before-- \1 --delete-after--/' | sed 's/.*--delete-before-- //' | sed 's/ --delete-after--.*//'`

lamp_php4_configure="configure  --prefix=/usr/local/php4  --with-config-file-path=/etc/php4/  --with-config-file-scan-dir=/etc/php4/config/ --with-pear=/usr/local/php4/pear/ --with-libxml-dir --with-openssl --with-pcre-regex --with-zlib --with-bz2 --with-curl --with-libxml-dir --with-xsl --with-gd --with-jpeg-dir --with-png-dir --with-zlib-dir --with-xpm-dir --with-freetype-dir --with-gettext --with-mhash --with-iconv --with-imap --with-imap-ssl --with-mcrypt --with-mysql --with-zlib-dir --with-pdo-mysql --with-kerberos  --enable-cli  --enable-ipv6 --enable-bcmath --enable-calendar --enable-dom --enable-exif --enable-ftp --enable-zip --enable-gd-native-ttf --enable-json --enable-mbstring --enable-mbregex --enable-mbregex-backtrack --enable-pcntl --enable-pdo --enable-simplexml --enable-soap --enable-tokenizer"
lamp_php52_configure="configure --prefix=/usr/local/php52 --with-config-file-path=/etc/php52/ --with-config-file-scan-dir=/etc/php52/config/ --with-pear=/usr/local/php52/pear/ --with-libxml-dir --with-openssl --with-pcre-regex --with-zlib --with-bz2 --with-curl --with-libxml-dir --with-xsl --with-gd --with-jpeg-dir --with-png-dir --with-zlib-dir --with-xpm-dir --with-freetype-dir --with-gettext --with-mhash --with-iconv --with-imap --with-imap-ssl --with-mcrypt --with-mysql --with-zlib-dir --with-pdo-mysql --with-kerberos  --enable-cli  --enable-ipv6 --enable-bcmath --enable-calendar --enable-dom --enable-exif --enable-ftp --enable-zip --enable-gd-native-ttf --enable-json --enable-mbstring --enable-mbregex --enable-mbregex-backtrack --enable-pcntl --enable-pdo --enable-simplexml --enable-soap --enable-tokenizer"
lamp_php53_configure="configure --prefix=/usr/local/php53 --with-config-file-path=/etc/php53/ --with-config-file-scan-dir=/etc/php53/config/ --with-pear=/usr/local/php53/pear/ --with-libxml-dir --with-openssl --with-pcre-regex --with-zlib --with-bz2 --with-curl --with-libxml-dir --with-xsl --with-gd --with-jpeg-dir --with-png-dir --with-zlib-dir --with-xpm-dir --with-freetype-dir --with-gettext --with-mhash --with-iconv --with-imap --with-imap-ssl --with-mcrypt --with-mysql --with-zlib-dir --with-pdo-mysql=mysqlnd --with-kerberos  --enable-cli  --enable-ipv6 --enable-bcmath --enable-calendar --enable-dom --enable-exif --enable-fileinfo --enable-ftp --enable-mysqlnd --enable-mysqlnd-compression-support --enable-zip --enable-gd-native-ttf --enable-intl --enable-json --enable-mbstring --enable-mbregex --enable-mbregex-backtrack --enable-pcntl --enable-pdo --enable-phar --enable-simplexml --enable-soap --enable-tokenizer"
lamp_php54_configure="configure --prefix=/usr/local/php54 --with-config-file-path=/etc/php54/ --with-config-file-scan-dir=/etc/php54/config/ --with-pear=/usr/local/php54/pear/ --with-libxml-dir --with-openssl --with-pcre-regex --with-zlib --with-bz2 --with-curl --with-libxml-dir --with-xsl --with-gd --with-jpeg-dir --with-png-dir --with-zlib-dir --with-xpm-dir --with-freetype-dir --with-gettext --with-mhash --with-iconv --with-imap --with-imap-ssl --with-mcrypt --with-mysql --with-zlib-dir --with-pdo-mysql=mysqlnd --with-kerberos  --enable-cli  --enable-ipv6 --enable-bcmath --enable-calendar --enable-dom --enable-exif --enable-fileinfo --enable-ftp --enable-mysqlnd --enable-mysqlnd-compression-support --enable-zip --enable-gd-native-ttf --enable-intl --enable-json --enable-mbstring --enable-mbregex --enable-mbregex-backtrack --enable-pcntl --enable-pdo --enable-phar --enable-simplexml --enable-soap --enable-tokenizer"
